package web

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
	"github.com/jcambass/tailhopper/internal/registry"
	"github.com/jcambass/tailhopper/internal/ui"
)

// tailnetStartHandler handles POST /tailnet/{id}/start
func tailnetStartHandler(reg *registry.Registry) http.HandlerFunc {
	return tailnetCommandHandler("start", reg.Start)
}

// tailnetStopHandler handles POST /tailnet/{id}/stop
func tailnetStopHandler(reg *registry.Registry) http.HandlerFunc {
	return tailnetCommandHandler("stop", reg.Stop)
}

func tailnetCommandHandler(action string, command func(context.Context, int) error) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		id, ok := tailnetID(w, r)
		if !ok {
			return
		}

		if err := command(ctx, id); err != nil {
			if errors.Is(err, registry.ErrTailnetNotFound) {
				http.Error(w, err.Error(), http.StatusNotFound)
				return
			}
			slog.ErrorContext(ctx, "failed to "+action+" tailnet",
				slog.String("component", "httprequests"),
				slog.Any("error", err),
			)
			http.Error(w, err.Error(), http.StatusConflict)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

// tailnetDeleteHandler handles DELETE /tailnet/{id}
func tailnetDeleteHandler(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		id, ok := tailnetID(w, r)
		if !ok {
			return
		}

		if err := reg.Delete(id); err != nil {
			if errors.Is(err, registry.ErrTailnetNotFound) {
				http.Error(w, err.Error(), http.StatusNotFound)
				return
			}
			slog.ErrorContext(ctx, "failed to delete tailnet",
				slog.String("component", "httprequests"),
				slog.Any("error", err),
			)
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		slog.InfoContext(ctx, "tailnet deleted successfully",
			slog.String("component", "httprequests"),
		)
		toastHTML, err := ui.RenderToast("success", "Tailnet deleted successfully")
		if err != nil {
			slog.ErrorContext(ctx, "failed to render toast",
				slog.String("component", "httprequests"),
				slog.Any("error", err),
			)
			return
		}

		w.Header().Set("Content-Type", "text/html")
		w.WriteHeader(http.StatusOK)
		fmt.Fprint(w, toastHTML)
	}
}

// addTailnetHandler handles POST /tailnet/add for creating a new tailnet.
func addTailnetHandler(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		id, err := reg.Add("") // Empty hostname will be auto-generated by registry
		if err != nil {
			if errors.Is(err, registry.ErrUnconfiguredTailnet) {
				http.Error(w, err.Error(), http.StatusConflict)
				return
			}
			slog.ErrorContext(ctx, "failed to add tailnet",
				slog.String("component", "httprequests"),
				slog.Any("error", err),
			)
			http.Error(w, fmt.Sprintf("failed to add tailnet: %v", err), http.StatusBadRequest)
			return
		}

		// Automatically start the new tailnet
		if err := reg.Start(r.Context(), id); err != nil {
			slog.ErrorContext(ctx, "failed to start new tailnet",
				slog.String("component", "httprequests"),
				slog.Any("error", err),
			)
			// Don't fail the request, the tailnet was created successfully
		}

		w.WriteHeader(http.StatusCreated)
	}
}

func tailnetID(w http.ResponseWriter, r *http.Request) (int, bool) {
	raw := chi.URLParam(r, "id")
	id, err := strconv.Atoi(raw)
	if err == nil {
		return id, true
	}
	slog.WarnContext(r.Context(), "invalid tailnet id",
		slog.String("component", "httprequests"),
		slog.String("id", raw),
	)
	http.Error(w, "invalid tailnet id", http.StatusBadRequest)
	return 0, false
}
