// Package web provides HTTP server setup and routing for Tailhopper.
package web

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/jcambass/tailhopper/internal/logging"
	"github.com/jcambass/tailhopper/internal/pac"
	"github.com/jcambass/tailhopper/internal/ts"
	"github.com/jcambass/tailhopper/internal/ui"
)

// Server represents the HTTP server for Tailhopper.
type Server struct {
	server       *http.Server
	addr         string
	logger       *logging.Logger
	sseBroadcast *SSEBroadcaster
}

// NewServer creates and configures a new HTTP server.
func NewServer(addr string, registry *ts.Registry) *Server {
	logger := logging.Default().With("component", "httpserver")
	sseBroadcast := NewSSEBroadcaster(logger)

	// Wire up SSE notifications from registry
	registry.SetStateChangeNotifier(func(tailnetID string) {
		sseBroadcast.NotifyStateChange(tailnetID)
	})

	mux := http.NewServeMux()

	// Static files
	mux.Handle("/static/", ui.StaticHandler())

	// Redirects
	mux.Handle("/ui/", http.RedirectHandler("/", http.StatusTemporaryRedirect))

	// PAC file
	mux.Handle(pac.URLPath, withRequestLogging(pac.Handler(registry)))

	// SSE endpoint
	mux.Handle("/events", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		sseBroadcast.ServeSSE(w, r)
	}))

	// Dashboard
	mux.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/" {
			ui.ServeDashboard(w, r, registry)
			return
		}
		http.Error(w, "not found", http.StatusNotFound)
	}))

	// Tailnet handlers - must be registered before the general /tailnet/ pattern
	mux.Handle("/tailnet/add", withRequestLogging(createAddTailnetHandler(registry, sseBroadcast)))
	mux.Handle("/tailnet/", withRequestLogging(createTailnetHandler(registry, sseBroadcast)))

	rootHandler := withRequestContext(withRecovery(mux))

	return &Server{
		server: &http.Server{
			Addr:              addr,
			Handler:           rootHandler,
			ReadHeaderTimeout: 10 * time.Second,
		},
		addr:         addr,
		logger:       logger,
		sseBroadcast: sseBroadcast,
	}
}

// Start begins serving HTTP requests (blocking).
func (s *Server) Start() error {
	s.logger.Printf("PAC file available at http://%s%s", s.addr, pac.URLPath)
	s.logger.Printf("Dashboard available at http://%s", s.addr)
	return s.server.ListenAndServe()
}

// createTailnetHandler returns an HTTP handler for tailnet start/stop operations.
// Path format: /tailnet/{id}/start or /tailnet/{id}/stop
func createTailnetHandler(registry *ts.Registry, sseBroadcast *SSEBroadcaster) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		logger := logging.FromContext(r.Context())

		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		// Extract tailnet ID and action from path: /tailnet/{id}/start or /tailnet/{id}/stop
		pathWithoutPrefix := strings.TrimPrefix(r.URL.Path, "/tailnet/")
		parts := strings.Split(pathWithoutPrefix, "/")
		if len(parts) != 2 {
			http.Error(w, "invalid path", http.StatusNotFound)
			return
		}

		id := parts[0]
		action := parts[1]

		if id == "" {
			http.Error(w, "missing tailnet id", http.StatusBadRequest)
			return
		}

		if action != "start" && action != "stop" {
			http.Error(w, "invalid action, must be 'start' or 'stop'", http.StatusBadRequest)
			return
		}

		tailnet, ok := registry.Get(id)
		if !ok {
			http.Error(w, "tailnet not found", http.StatusNotFound)
			return
		}

		if action == "start" {
			if err := tailnet.Start(r.Context()); err != nil {
				logger.Printf("failed to start tailnet: %v", err)
				http.Error(w, err.Error(), http.StatusConflict)
				return
			}
			w.WriteHeader(http.StatusNoContent)
		} else { // stop
			if err := tailnet.Stop(r.Context()); err != nil {
				logger.Printf("failed to stop tailnet: %v", err)
				http.Error(w, err.Error(), http.StatusConflict)
				return
			}
			w.WriteHeader(http.StatusNoContent)
		}

		// Note: SSE broadcasts state changes.
	})
}

// createAddTailnetHandler returns an HTTP handler for creating a new tailnet.
func createAddTailnetHandler(registry *ts.Registry, sseBroadcast *SSEBroadcaster) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		logger := logging.FromContext(r.Context())

		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		// Check if there are any unconfigured tailnets
		if registry.HasUnconfiguredTailnets() {
			logger.Printf("cannot add new tailnet: unconfigured tailnet exists")
			http.Error(w, "cannot create new tailnet while an existing tailnet is unconfigured", http.StatusConflict)
			return
		}

		tailnet, err := registry.Add("") // Empty hostname will be auto-generated by registry
		if err != nil {
			logger.Printf("failed to add tailnet: %v", err)
			http.Error(w, fmt.Sprintf("failed to add tailnet: %v", err), http.StatusBadRequest)
			return
		}

		// Automatically start the new tailnet
		if err := tailnet.Start(r.Context()); err != nil {
			logger.Printf("failed to start new tailnet: %v", err)
			// Don't fail the request, the tailnet was created successfully
		}

		// Notify about new tailnet (registry also sends notification, but this ensures immediate update)
		sseBroadcast.NotifyGlobalChange()

		w.WriteHeader(http.StatusCreated)
	})
}

type requestIDKey struct{}

func withRequestContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestID := r.Header.Get("X-Request-Id")
		if requestID == "" {
			requestID = newRequestID()
		}
		w.Header().Set("X-Request-Id", requestID)

		logger := logging.Default().WithFields(map[string]string{
			"component":  "httprequests",
			"request_id": requestID,
		})
		ctx := context.WithValue(r.Context(), requestIDKey{}, requestID)
		ctx = logging.WithContext(ctx, logger)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

func newRequestID() string {
	buffer := make([]byte, 16)
	if _, err := rand.Read(buffer); err != nil {
		return "unknown"
	}
	return hex.EncodeToString(buffer)
}

func withRecovery(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		logger := logging.FromContext(r.Context())
		defer logging.CatchPanic(logger)
		next.ServeHTTP(w, r)
	})
}

// responseWriter wraps http.ResponseWriter to capture the status code
type responseWriter struct {
	http.ResponseWriter
	statusCode int
	written    bool
}

func (rw *responseWriter) WriteHeader(code int) {
	if !rw.written {
		rw.statusCode = code
		rw.written = true
		rw.ResponseWriter.WriteHeader(code)
	}
}

func (rw *responseWriter) Write(b []byte) (int, error) {
	if !rw.written {
		rw.statusCode = http.StatusOK
		rw.written = true
	}
	return rw.ResponseWriter.Write(b)
}

func withRequestLogging(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		logger := logging.FromContext(r.Context())
		logger.Printf("Request: %s %s from %s", r.Method, r.URL.Path, r.RemoteAddr)

		rw := &responseWriter{ResponseWriter: w, statusCode: http.StatusOK}
		next.ServeHTTP(rw, r)

		logger.Printf("Response: %s %s -> %d", r.Method, r.URL.Path, rw.statusCode)
	})
}
